# Generated by Django 5.2.5 on 2025-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('faculty_id', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
    ]
