# Generated by Django 5.2.5 on 2025-10-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('DSE', 'Data Science and Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('MVLSI', 'Microelectronics and Very Large Scale Integration'), ('EP', 'Engineering Physics'), ('GE', 'General Engineering'), ('MnC', 'Mathematics and Computing'), ('MSE', 'Material Science and Engineering'), ('BioEng', 'Bioengineering'), ('BS_CS', 'Bachelor of Science in Chemical Science')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('LTPC', models.CharField(max_length=20)),
                ('status', models.CharField(default='Yes', max_length=20)),
                ('slot', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('FS', 'FS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SCEE', 'School of Computing and Electrical Engineering (SCEE)'), ('SMSS', 'School of Mathematics & Statistical Sciences (SMSS)'), ('SPS', 'School of Physical Sciences (SPS)'), ('SBB', 'School of Biosciences & Bioengineering (SBB)'), ('SCENE', 'School of Civil & Environmental Engineering (SCENE)'), ('SMME', 'School of Mechanical and Materials Engineering (SMME)'), ('SCS', 'School of Chemical Sciences (SCS)')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='Registration.course')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CourseBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.branch')),
                ('categories', models.ManyToManyField(blank=True, related_name='course_branches', to='Registration.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.course')),
            ],
            options={
                'unique_together': {('course', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(related_name='courses', through='Registration.CourseBranch', to='Registration.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Registration.department'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile_no', models.BigIntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(related_name='courses', to='Registration.faculty'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('semester', models.IntegerField(default=1, null=True)),
                ('mobile_no', models.BigIntegerField(null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.branch')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ENR', 'Enrolled'), ('CMP', 'Completed'), ('DRP', 'Dropped')], default='PND', max_length=3)),
                ('outcome', models.CharField(choices=[('UNK', 'Unknown'), ('PAS', 'Pass'), ('FAI', 'Fail')], default='UNK', max_length=3)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F'), ('FS', 'FS')], max_length=3, null=True)),
                ('is_pass_fail', models.BooleanField(default=False)),
                ('semester', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Registration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Registration.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='Registration.StudentCourse', to='Registration.course'),
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DC', 'Disciplinary Core (DC)'), ('DE', 'Disciplinary Elective (DE)'), ('IC', 'Institute Core (IC)'), ('HSS', 'Humanities and Social Science (HSS)'), ('FE', 'Free Elective (FE)'), ('IKS', 'Indian Knowledge System (IKS)'), ('ISTP', 'Interactive Socio-Technical Practicum (ISTP)'), ('MTP', 'Major Technical Project (MTP)')], max_length=4)),
                ('required_credits', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Registration.branch')),
            ],
            options={
                'unique_together': {('branch', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Registration.assessmentcomponent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='Registration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='Registration.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'component')},
            },
        ),
    ]
