# Generated by Django 5.2.5 on 2025-09-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='coursebranch',
            name='category',
        ),
        migrations.AddField(
            model_name='coursebranch',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='course_branches', to='Registration.category'),
        ),
    ]
