# Generated by Django 5.2.5 on 2025-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='branch',
        ),
        migrations.AddField(
            model_name='faculty',
            name='mobile_no',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
