# Generated by Django 5.2.5 on 2025-10-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='Registration.course')),
            ],
            options={
                'unique_together': {('course', 'semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Registration.assessmentcomponent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='Registration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='Registration.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester', 'component')},
            },
        ),
    ]
