# Generated by Django 5.2.5 on 2025-08-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_remove_faculty_branch_faculty_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
