# Generated by Django 5.2.5 on 2025-10-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_assessmentcomponent_assessmentscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together={('course', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('student', 'course', 'component')},
        ),
        migrations.RemoveField(
            model_name='assessmentcomponent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='semester',
        ),
    ]
