# Generated by Django 5.2.5 on 2025-09-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_category_remove_coursebranch_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
