# Generated by Django 5.2.5 on 2025-08-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_faculty_mobile_no_alter_student_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('course_type', models.CharField(choices=[('IC', 'Interdisciplinary Core'), ('DC', 'Discipline Core'), ('FE', 'Free Elective'), ('DE', 'Discipline Elective')], max_length=2)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Registration.faculty')),
            ],
        ),
    ]
