# Generated by Django 5.2.5 on 2025-09-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_studentcourse_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursebranch',
            unique_together={('course', 'branch')},
        ),
    ]
