# Generated by Django 5.2.5 on 2025-08-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_faculty_mobile_no_alter_student_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_id',
        ),
    ]
