# Generated by Django 5.2.5 on 2025-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_feerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='is_pass_fail',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course_mode',
            field=models.CharField(choices=[('REG', 'Regular'), ('PF', 'Pass/Fail'), ('AUD', 'Audit')], default='REG', max_length=3),
        ),
    ]
