# Generated by Django 5.2.5 on 2025-08-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
    ]
