# Generated by Django 5.2.5 on 2025-11-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_admins_results_deadline_admins_results_mode'),
        ('Registration', '0005_remove_studentcourse_is_pass_fail_and_more'),
    ]

    operations = [
    ]
