# Generated by Django 5.2.5 on 2025-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_rename_admin_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
