# Generated by Django 5.2.5 on 2025-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_merge_20251107_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_active_pre_reg',
            field=models.BooleanField(default=True),
        ),
    ]
