# Generated by Django 5.2.5 on 2025-09-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_alter_student_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('LTPC', models.CharField(max_length=20)),
                ('slot', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('FS', 'FS')], max_length=2)),
                ('faculties', models.ManyToManyField(related_name='courses', to='Registration.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DC', 'Disciplinary Core (DC)'), ('DE', 'Disciplinary Elective (DE)'), ('IC', 'Institute Core (IC)'), ('HSS', 'Humanities and Social Science (HSS)'), ('FE', 'Free Elective (FE)'), ('IKS', 'Indian Knowledge System (IKS)'), ('ISTP', 'Interactive Socio-Technical Practicum (ISTP)'), ('MTP', 'Major Technical Project (MTP)')], max_length=4)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(related_name='courses', through='Registration.CourseBranch', to='Registration.branch'),
        ),
    ]
