# Generated by Django 5.2.5 on 2025-11-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_studentcourse_is_active_pre_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ABS', 'Absolute'), ('REL', 'Relative')], default='ABS', max_length=3)),
                ('abs_cutoffs', models.JSONField(blank=True, default=dict)),
                ('rel_buckets', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_policy', to='Registration.course')),
            ],
        ),
    ]
